apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garmin-db-pvc
  namespace: garmin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-path
