apiVersion: v1
kind: Namespace
metadata:
  name: garmin-n8n
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: garmin-mariadb
  namespace: garmin-n8n
spec:
  volumeClaimTemplate:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    storageClassName: longhorn
  image: mariadb:11.4
  rootPasswordSecretKeyRef:
    name: garmin-mariadb-credentials
    key: password
  username: garmindb
  passwordSecretKeyRef:
    name: garmin-mariadb-credentials
    key: password
  database: garmindb
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

